const STRATEGY_CONFIGS = {
    // Single structure strategies
    'Call Option': { dualPanel: false },
    'Put Option': { dualPanel: false },
    'Vertical Call Spread': { dualPanel: false },
    'Vertical Put Spread': { dualPanel: false },
    'Straddle': { dualPanel: false },
    'Strangle': { dualPanel: false },
    'Call Fly': { dualPanel: false },
    'Put Fly': { dualPanel: false },
    'Iron Butterfly': { dualPanel: false },
    'Call Condor': { dualPanel: false },
    'Put Condor': { dualPanel: false },
    'Iron Condor': { dualPanel: false },
    'Fence': { dualPanel: false },

    // Dual structure strategies
    'Calendar Call Spread': { dualPanel: true },
    'Calendar Put Spread': { dualPanel: true },
    'Calendar Straddle': { dualPanel: true },
    'Calendar Strangle': { dualPanel: true },
    'Horizontal Call Spread': { dualPanel: true },
    'Horizontal Put Spread': { dualPanel: true },
    'Diagonal Call Spread': { dualPanel: true },
    'Diagonal Put Spread': { dualPanel: true },
    'Diagonal Straddle Spread': { dualPanel: true },
    'Straddle Spread': { dualPanel: true },
    '3-Way: Call Spread v Put': { dualPanel: true },
    '3-Way: Put Spread v Call': { dualPanel: true },
    '3-Way: Straddle v Call': { dualPanel: true },
    '3-Way: Straddle v Put': { dualPanel: true },
    'Conversion/Reversal': { dualPanel: true },
    'Call Tree': { dualPanel: true },
    'Put Tree': { dualPanel: true }
};